nx = 24; ny = 24;
dx = 2*pi / nx;
dy = 2*pi / ny;
x = linspace(0, 2*pi - dx, nx);
y = linspace(0, 2*pi - dy, ny);
[X, Y] = meshgrid(y, x);
fun = @(x, y) sin(x) .* cos(y) + 0.5 * cos(2*x - y);
u = fun(X, Y);
degree_x = 3;
degree_y = 3;
interp = periodic_bspline_interpolant_2d(u, degree_x, degree_y);
xq = linspace(0, 2*pi, 100);
yq = linspace(0, 2*pi, 100);
[XQ, YQ] = meshgrid(yq, xq);
vq = interp.evaluate(XQ, YQ);
true_vals = fun(XQ, YQ);
figure('Position', [100, 100, 1200, 500]);
subplot(2,2,1);
imagesc(xq, yq, vq');
axis xy; colorbar;
title('Periodic B-spline Interpolant (2D)');
xlabel('x'); ylabel('y');
subplot(2,2,2);
imagesc(xq, yq, true_vals);
axis xy; colorbar;
title('True Function');
xlabel('x'); ylabel('y');
subplot(2,2,3);
plot(xq, vq(:,10), 'DisplayName', 'interp');
hold on;
plot(xq, true_vals(10,:), '--', 'DisplayName', 'true');
legend;
title('Slice at y = yq(10)');